### ISSUE TITLE
Circles not visibles on Firefox 47

### ISSUE THREAD

**Issue by samuel-22** [radekmie/react-timepicker#1]
Circles are not visible because the "r" css property isn't handled
http://stackoverflow.com/questions/14255631/style-svg-circle-with-css

**Comment by radekmie** [comment]
Thanks, @samuel-22 - I didn't knew that!

Now there's a problem - if I _simply_ move it from CSS to an attribute, then it will be a breaking change...

**Comment by radekmie** [comment]
OK, it's fixed in `v1.1.5`. I've also fixed text alignment issue in `v1.1.4`.
