### ISSUE TITLE
React 16 issue

### ISSUE THREAD

**Issue by orouz** [radekmie/react-timepicker#10]
hey! cool stuff :) 
i've upgraded React to v16 and it doesn't seem to work with it. 

here's the relevant stack trace: 
```
timepicker.js:1 Uncaught ReferenceError: positions is not defined
    at b.calculatePositionsHours (timepicker.js:1)
    at new b (timepicker.js:1)
```

if you'd add the source files to the repo (not just the minified) i'd be happy to take a look.

**Comment by orouz** [comment]
so you did include the source files :) 
PR at #11

**Comment by radekmie** [comment]
Check out v2.0.1.

EDIT:
Check out v2.0.2.

**Comment by orouz** [comment]
awesome! :)
