### ISSUE TITLE
Wrong import in 'Quick Start' example

### ISSUE THREAD

**Issue by GuillemotF** [radekmie/react-timepicker#13]
Hi, nice work on this TimePicker.

You're importing `Timepicker` as default in your example but there's no default export in your component file.

I suggest to export `Timepicker` as default or correct the import in the example. 
Btw you can also show the css import to demonstrate a full working example :

```
import { Timepicker } from 'react-timepicker';
import 'react-timepicker/timepicker.css';
```

**Comment by radekmie** [comment]
Thank for pointing it out, @GuillemotF. I'll submit an update in few minutes.
