### ISSUE TITLE
formatNumber prop should handle formatting of numerals in bubbles differently than numerals displayed in the value at the top.

### ISSUE THREAD

**Issue by rucsin** [radekmie/react-timepicker#4]
using prop formatNumber, the numbers in the balls are represented the same as in the value at the top. 
E.g., In the balls the numbers gets displayed the same e.g. '03' instead of '3'. For values '03' is ok but for the balls '3' should be applied.
 Can represenation of numerals in value on top be different from what is displayed in balls(without '0').

**Comment by radekmie** [comment]
From v1.3.0 `formatNumber` have an additional parameter - take a look at the readme.

**Comment by rucsin** [comment]
If I use this as:
formatNumber = (num: number, info: 'info') => return num < 10 ? Number('0').toLocaleString('en') + num.toLocaleString('en') : num.toLocaleString('en');

I get both clock numerals and info numerals having numerals e.g. '03'. Can you suggest what's being missed out in my usage that it does not work. Also I'm not sure if we can use this for multiple purposes so that one should apply to both 'info' and 'clock' and the others should apply to 'info' only.
For example,  I need to use formatNumber to 
1) display all numerals in respective locales e.g. 'ar'
2) concatenating with '0' should get applied to 'info' only and not 'clock'.

**Comment by radekmie** [comment]
It's not a question about this package but about the JS itself - try something and use the Google and StackOverflow.
