### ISSUE TITLE
Support for React 16.0?

### ISSUE THREAD

**Issue by awhillas** [radekmie/react-timepicker#6]
Two warning:

> Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
    console.warn node_modules/react/lib/lowPriorityWarning.js:40

> Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class

Any plans to catch up with this?

**Comment by radekmie** [comment]
Hey, @awhillas. Yeah, sure it's doable. Maybe you'd like to submit a PR for it?

**Comment by radekmie** [comment]
Hello @awhillas. Could you try the `v2.0.0-alpha.0` version?
