### ISSUE TITLE
Time picker does not automatically switch to minutes clock when hour is selected

### ISSUE THREAD

**Issue by leenakumar80** [radekmie/react-timepicker#7]
This does not happen when run locally. But when deployed to other enevironments to be tested, the picker 
 immediately closes on selecting hour. Do you have any suggestions what results in this behaviour?

**Comment by radekmie** [comment]
Could you say something more? Which browser or operating system?

**Comment by leenakumar80** [comment]
I have used Windows 10, browser Chrome.

**Comment by leenakumar80** [comment]
One of our developers was able to mitigate the bug consequences by removing functionality, that differentiates if user was trying to click an hour or drag and drop. I assume that user always wants just click.

**Comment by radekmie** [comment]
I've tried to reproduce it on Linux (I don't have Windows) and I wasn't able to do it.

**Comment by radekmie** [comment]
Could you try the v2.0.0-alpha.0 version? I haven't changed much, but React version might be related.

**Comment by leenakumar80** [comment]
Doesn't seem stable with this version.

**Comment by leenakumar80** [comment]
still doesn't work with latest version 2.0.2

**Comment by leenakumar80** [comment]
This time I ran locally but on azure. so I can reproduce it locally as well but on another server (azure).

**Comment by radekmie** [comment]
But it’s completely **not** related. Only React and browser (including OS) version matter.

**Comment by leenakumar80** [comment]
The problem is (using latest version 2.0.2) , when user selects any hour, it does switch to minutes mode but comes back to hour mode back. This happens so quickly that it's not noticeable until debugged where you can see how it navigates from hour->minutes and back to minutes mode.

**Comment by leenakumar80** [comment]
The problem is (using latest version 2.0.2) , when user selects any hour, it does switch to minutes mode but comes back to hour mode back. This happens so quickly that it's not noticeable until debugged where you can see how it navigates from hour->minutes and back to hours mode.

**Comment by radekmie** [comment]
As I said - I'm not able to reproduce it. I'll surely accept a PR for it but (at least now) I can't debug it.
